spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        package-to-scan: com.barbosa.fakeapi.infrastructure.entities
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enable: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

topico:
  fake-api:
    consumer:
      nome: fake-api-consumer-products-v2
      group-id: barbosas
    producer:
      nome: fake-api-producer-products-v2

fake-api:
  url: https://fakestoreapi.com

server:
  port: 8181

send:
  mail:
    to:
    from:
